### ISSUE TITLE
Build not using mirth.version from pom.xml

### ISSUE THREAD

**Issue by joshmc82** [kpalang/mirth-sample-plugin#7]
It appears that just updating `mirth.version` in pom.xml is not sufficient. I also need to set `plugin.mirthVersion` to match else it will always build against what is in `plugin.mirthVersion`

Steps to reproduce:

1. Clone fresh copy of this repo
2. Edit pom.xml in the root directory and set `mirth.version` to 4.1.1
3. Save pom.xml
4. `mvn install`
5. `mvn clean package`
6. navigate to target folder
7. unzip plugintest.zip
8. open plugintest/plugin.xml
9. verify `mirthVersion` is not 4.1.1 as expected

**Comment by jonbartels** [comment]
https://github.com/kpalang/mirth-sample-plugin/search?q=mirth.version shows the issue. `mirth.version` and `plugin.mirthVersion` are both used interchangeably. 

Also note that `plugin.xml` ultimately accepts a comma separated list of supported MC versions. This may not be practical to map in maven though since maven wants one version to build its dependencies.

**Comment by tonygermano** [comment]
They are not interchangeable.

`mirth.version` specifies the mirth version you are building against when pulling the maven dependencies.

`plugin.mirthVersion` specifies what goes into the `plugin.xml`, and it will accept a comma separated list of supported MC versions.
